[package]
name = "chat_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = {workspace=true}
argon2 = { version = "0.5.3", features = ["std"] }
axum = {workspace=true}
chrono = { version = "0.4.38", features = ["serde"] }
serde = {workspace=true}
serde_yaml = {workspace=true}
jwt-simple = "0.12"
sqlx = { workspace = true, features = ["postgres", "runtime-tokio", "tls-rustls","chrono"] }
thiserror = {workspace=true}
tokio = {workspace=true}
tracing = {workspace=true}
tracing-subscriber = {workspace=true}
http-body-util = "0.1.2"
serde_json = "1.0.117"


[dev-dependencies]
sqlx-db-tester = "0.4.2"
