### signup user

POST http://localhost:6688/api/signup
Content-Type: application/json

{
    "name": "Takiki",
    "email": "Takiki@gmail.com",
    "password": "takitaki",
    "workspace": "1"
}

### signin user (valid)
# @name signin

POST http://localhost:6688/api/signin
Content-Type: application/json

{
    "email": "Taki@gmail.com",
    "password": "takitaki"
}

@token = {{signin.response.body.token}}


### signin user (invalid)

POST http://localhost:6688/api/signin
Content-Type: application/json

{
    "email": "alice@acme.org",
    "password": "123456"
}



### get chat list

GET http://localhost:6688/api/chats
Authorization: Bearer {{token}}


### create_chat

Post http://localhost:6688/api/chats
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "public": false,
    "members": [1,2]
}

### delete chat
DELETE http://localhost:6688/api/chat/4
Authorization: Bearer {{token}}


### update chat
PATCH http://localhost:6688/api/chat/5
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "members": [1,2]
}

### upload file
POST http://localhost:6688/api/upload
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=myboundary
Keep-Alive: timeout=5, max=1000

--myboundary
Content-Disposition: form-data; filename="aa.jpg"
Content-Type: application/octet-stream
Keep-Alive: timeout=5, max=1000

< /Users/taki/Pictures/wallpaper/aa.jpg

--myboundary
Content-Disposition: form-data; filename="bb.jpg"
Content-Type: image/jpeg
Keep-Alive: timeout=5, max=1000

< /Users/taki/Pictures/wallpaper/bb.jpg

--myboundary
Content-Disposition: form-data; filename="hello.txt"
Content-Type: text/plain
Keep-Alive: timeout=5, max=1000

hello world

--myboundary--



### upload file
GET http://localhost:6688/api/files/0/e6a/bae/bd5e0e6e37b75c7cacc3ca7496b8e9262b.png
Authorization: Bearer {{token}}
