### signup user

POST http://localhost:6688/api/signup
Content-Type: application/json

{
    "name": "Taki2222",
    "email": "Taki@gmail.com",
    "password": "takitaki",
    "workspace": "1"
}

### signin user (valid)
# @name signin

POST http://localhost:6688/api/signin
Content-Type: application/json

{
    "email": "Taki@gmail.com",
    "password": "takitaki"
}

@token = {{signin.response.body.token}}


### signin user (invalid)

POST http://localhost:6688/api/signin
Content-Type: application/json

{
    "email": "alice@acme.org",
    "password": "123456"
}



### get chat list


GET http://localhost:6688/api/chat
Authorization: Bearer {{token}}
